version: '3'
services:
  app:
    image: 'app-crud:backendv1'
    ports:
      - 8080:8080
    build:
      context: .
    container_name: spring
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - backendNetwork
      - frontendNetwork
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5403:5403
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
     - backendNetwork

  frontend:
      image: app-crud:frontendv1
      build: 
        context: .
      container_name: angular
      ports:
        - "4200:80"
      depends_on:
        - app
      networks:
      - frontendNetwork

networks:
  backendNetwork:
  frontendNetwork: